name: detour art
favicon: null
layout_spectrum: 0.4285308171529323
typography_spectrum: 0.40073
title: detour art on the grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.21873309300281107
  lightness: 0.6824342650361359
  saturation: 0.3466779706068337
  rhythmicContrast: 0.5473986410070211
purpose: []
